# Generated by Django 4.1.3 on 2022-11-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
