# Generated by Django 4.1.3 on 2022-11-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='studs',
        ),
    ]
