# Generated by Django 4.1.3 on 2023-01-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studs_email_alter_studs_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('atten', models.BooleanField(default=False)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studs')),
            ],
        ),
    ]
