# Generated by Django 4.1.3 on 2023-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studs',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
