# Generated by Django 4.1.3 on 2023-01-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studs_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='atten',
            new_name='attend',
        ),
        migrations.AlterField(
            model_name='studs',
            name='roll',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
