# Generated by Django 4.1.3 on 2023-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studs',
            name='roll',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
